version: "3.9"
services:
  backend:
    image: balajimalali/testapp
    container_name: backend
    ports:
     - 8080:8080
    restart: always
    volumes:
      - ./:/app
    
  frontend:
    image: balajimalali/testapp-frontend
    container_name: frontend
    ports:
     - 80:3000
    depends_on:
      - backend
    restart: always
